








declare const Bun: {
  Glob: new (pattern: string) => { scanSync: (cwd: string) => Iterable<string> };
  file: (path: string) => { text: () => Promise<string> };
  write: (path: string, data: string) => Promise<number>;
};

/** packages/web/src — resolved from this file, so the caller's cwd does not matter. */
export const SRC = new URL("../src/", import.meta.url).pathname;

 
const CALL = /\b(?:t|tp|msg)\(\s*"((?:[^"\\]|\\.)*)"|\btranslate(?:Plural)?\([^,]{0,40},\s*"((?:[^"\\]|\\.)*)"/g;

 
const unescapeLiteral = (raw: string): string => {
  try {
    return JSON.parse(`"${raw}"`) as string;
  } catch {
    return raw;
  }
};

export async function extract(): Promise<string[]> {
  const found = new Set<string>();
  for (const f of new Bun.Glob("**/*.{ts,tsx}").scanSync(SRC)) {
    if (f.includes("messages.generated") || f.includes("i18n/locales/")) continue;  
    const src = await Bun.file(SRC + f).text();
    for (const m of src.matchAll(CALL)) found.add(unescapeLiteral((m[1] ?? m[2])!));
  }
  return [...found].sort();
}

 
export async function writeMessages(): Promise<number> {
  const msgs = await extract();
  await Bun.write(
    `${SRC}lib/i18n/messages.generated.ts`,
    "// GENERATED by `bun run i18n:extract` — do not edit. The English source IS the key.\n" +
      `export const MESSAGES = ${JSON.stringify(msgs, null, 2)} as const;\n` +
      "export type Message = (typeof MESSAGES)[number];\n",
  );
  return msgs.length;
}
