/**
 * Message extraction (pure) — shared by `bun run i18n:extract` and src/lib/i18n/i18n.test.ts.
 *
 * The message IS the key, so the canonical list of messages is whatever the SOURCE says: every
 * `t("…")`, `tp("…", n)`, `msg("…")` and `translate(lang, "…")` in packages/web/src.
 *
 * Bun's globals are declared locally instead of imported: this file is pulled into the web
 * typecheck by the test, and packages/web installs neither @types/node nor bun-types.
 */
declare const Bun: {
  Glob: new (pattern: string) => { scanSync: (cwd: string) => Iterable<string> };
  file: (path: string) => { text: () => Promise<string> };
  write: (path: string, data: string) => Promise<number>;
};

/** packages/web/src — resolved from this file, so the caller's cwd does not matter. */
export const SRC = new URL("../src/", import.meta.url).pathname;

/** `t("…")` / `tp("…")` / `msg("…")`, and `translate(lang, "…")` / `translatePlural(lang, "…")`. */
const CALL = /\b(?:t|tp|msg)\(\s*"((?:[^"\\]|\\.)*)"|\btranslate(?:Plural)?\([^,]{0,40},\s*"((?:[^"\\]|\\.)*)"/g;

/** A source literal is escaped ("…\n…"); the MESSAGE is the string it denotes. */
const unescapeLiteral = (raw: string): string => {
  try {
    return JSON.parse(`"${raw}"`) as string;
  } catch {
    return raw;
  }
};

export async function extract(): Promise<string[]> {
  const found = new Set<string>();
  for (const f of new Bun.Glob("**/*.{ts,tsx}").scanSync(SRC)) {
    if (f.includes("messages.generated") || f.includes("i18n/locales/")) continue; // generated / translated
    const src = await Bun.file(SRC + f).text();
    for (const m of src.matchAll(CALL)) found.add(unescapeLiteral((m[1] ?? m[2])!));
  }
  return [...found].sort();
}

/** Rewrites src/lib/i18n/messages.generated.ts. Returns the message count. */
export async function writeMessages(): Promise<number> {
  const msgs = await extract();
  await Bun.write(
    `${SRC}lib/i18n/messages.generated.ts`,
    "// GENERATED by `bun run i18n:extract` — do not edit. The English source IS the key.\n" +
      `export const MESSAGES = ${JSON.stringify(msgs, null, 2)} as const;\n` +
      "export type Message = (typeof MESSAGES)[number];\n",
  );
  return msgs.length;
}
