/**
 * Message extraction (pure) — shared by `bun run i18n:extract` and src/lib/i18n/i18n.test.ts.
 *
 * The message IS the key, so the canonical list of messages is whatever the SOURCE says: every
 * `t("…")`, `tp("…", n)`, `msg("…")` and `translate(lang, "…")` in packages/web/src.
 *
 * Bun's globals are declared locally instead of imported: this file is pulled into the web
 * typecheck by the test, and packages/web installs neither @types/node nor bun-types.
 */
declare const Bun: {
  Glob: new (pattern: string) => { scanSync: (cwd: string) => Iterable<string> };
  file: (path: string) => { text: () => Promise<string> };
  write: (path: string, data: string) => Promise<number>;
};

/** packages/web/src — resolved from this file, so the caller's cwd does not matter. */
export const SRC = new URL("../src/", import.meta.url).pathname;

/** `t("…")` / `tp("…")` / `msg("…")`, and `translate(lang, "…")` / `translatePlural(lang, "…")`. */
const CALL = /\b(?:t|tp|msg)\(\s*"((?:[^"\\]|\\.)*)"|\btranslate(?:Plural)?\([^,]{0,40},\s*"((?:[^"\\]|\\.)*)"/g;

/** A source literal is escaped ("…\n…"); the MESSAGE is the string it denotes. */
const unescapeLiteral = (raw: string): string => {
  try {
    return JSON.parse(`"${raw}"`) as string;
  } catch {
    return raw;
  }
};

/**
 * Pure matcher: every message literal in ONE source text, with the 1-based line of its call.
 * Deliberately matched against the WHOLE text, not line by line: the formatter wraps calls
 * longer than the line width, so `t(` and its string literal legally live on different lines —
 * a line-based matcher silently drops those messages and orphans their translations.
 */
export function matchMessages(src: string): { message: string; line: number }[] {
  const out: { message: string; line: number }[] = [];
  let line = 1;
  let counted = 0;
  for (const m of src.matchAll(CALL)) {
    for (let i = counted; i < m.index; i++) if (src.charCodeAt(i) === 10) line++;
    counted = m.index;
    out.push({ message: unescapeLiteral((m[1] ?? m[2])!), line });
  }
  return out;
}

/** Every message with the call sites ("file:line") that produce it — the raw material below. */
export async function extractSites(): Promise<Map<string, string[]>> {
  const sites = new Map<string, string[]>();
  for (const f of new Bun.Glob("**/*.{ts,tsx}").scanSync(SRC)) {
    if (f.includes("messages.generated") || f.includes("i18n/locales/")) continue; // generated / translated
    const src = await Bun.file(SRC + f).text();
    for (const { message, line } of matchMessages(src)) {
      const at = `${f}:${line}`;
      const seen = sites.get(message);
      if (seen) seen.push(at);
      else sites.set(message, [at]);
    }
  }
  return sites;
}

export async function extract(): Promise<string[]> {
  return [...(await extractSites()).keys()].sort();
}

/**
 * AMBIGUITY REPORT (design §2 — a WARNING, deliberately not a build gate).
 *
 * A SHORT message reused at several call sites hands the translator one word with no context, and
 * one translation then has to serve every context it appears in: the classic "Save" verb/noun trap.
 * It is how a bare "Type" — the imperative above the DELETE/RESET/DISABLE-E2EE confirmations —
 * shipped as the NOUN ("Typ", "Tipo") in 7 of 8 locales.
 *
 * Not a gate, because most hits are honest ("Transactions", "Cancel"): a human decides. The
 * resolution is the one the design prescribes — rephrase into a whole sentence with a placeholder,
 * which is also what i18n.test.ts's fragment ban forces for anything glued together in JSX.
 */
export function ambiguous(sites: Map<string, string[]>): { message: string; sites: string[] }[] {
  const candidates: { message: string; sites: string[] }[] = [];
  for (const [message, at] of sites) {
    if (at.length < 2) continue; // one call site → one context → no collision
    const words = message.trim().split(/\s+/).length;
    if (words > 2 || /[.?!:…]$/.test(message.trim()) || /\{\w+\}/.test(message)) continue; // a sentence carries its own context
    candidates.push({ message, sites: at });
  }
  return candidates.sort((a, b) => b.sites.length - a.sites.length || a.message.localeCompare(b.message));
}

/** Rewrites src/lib/i18n/messages.generated.ts. Returns the message count. */
export async function writeMessages(): Promise<number> {
  const msgs = await extract();
  await Bun.write(
    `${SRC}lib/i18n/messages.generated.ts`,
    "// GENERATED by `bun run i18n:extract` — do not edit. The English source IS the key.\n" +
      `export const MESSAGES = ${JSON.stringify(msgs, null, 2)} as const;\n` +
      "export type Message = (typeof MESSAGES)[number];\n",
  );
  return msgs.length;
}
